#%RAML 1.0 NamedExample
value:
  studentName: "Bharat"
  studentID: 17
  studentAddress: "at post jalaka bhadang"
  studentPhone: "9824799919"
  studentActive: "I"
  studentYear:  "8"
  studentSemester: 2